# NumPy


### What is NumPy?
NumPy is a short form for Numerical Python. Numpy is one of the most commonly used packages for scientific computing in Python. It provides a multidimensional array object, as well as variations such as masks and matrices, which can be used for various math operations. Numpy is compatible with, and used by many other popular Python packages, including pandas and matplotlib.
<br/>
    - Python library for creating N-dimensional arrays
    - Ability to quickly broadcast functions
    - Built-in linear algebra, statistical distributions, trigonometry, and random number capabilities

### Why use NumPy?
NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further
<br/>
    - While Numpy structures look similar to standard Python lists, they are much more efficient
    - The broadcasting capabilities are also extremely usefule for quickly applying functions to our data sets

## NumPy Arrays

In [2]:
import numpy as np

In [3]:
my_list = [1, 2, 3]

In [4]:
type(my_list)

list

In [5]:
#transform to numpy array
#note this action does not change the orginal list
np.array(my_list) 

array([1, 2, 3])

In [6]:
myArray = np.array(my_list) 

In [7]:
type(myArray)

numpy.ndarray

In [8]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#equivalent to Python's range function
#takes in: start, stop(exclusive), optional:step
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [11]:
#one-dimensional array of zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
#two-dimensional 5x5 array of zeros
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
#one-dimensional array of ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
#two-dimensional 5x5 array of ones
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
#takes in: start, stop, num: how many numbers evenly spaced
#ex: give me three numbers between 0 and 10, evenly spaced
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [16]:
#creates an identity matrix
#identity matrices are always square matrices (n x n)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
#creates a one-dimensional array with randomly generated numbers between 0(inclusive) and 1(exclusive)
#returns floats
np.random.rand(5)

array([0.18090457, 0.05463814, 0.62529946, 0.91820221, 0.16416558])

In [18]:
#creates a 5x2 matrix with randomly generated numbers between 0(inclusive) and 1(exclusive)
#returns floats
np.random.rand(5, 2)

array([[0.89929874, 0.69839991],
       [0.25420357, 0.72357228],
       [0.05961479, 0.76281692],
       [0.23467035, 0.43886602],
       [0.53623157, 0.20880588]])

In [19]:
#can include negative numbers
#creates a one-dimensional array with randomly generated numbers between 0(inclusive) and 1/-1(exclusive)
#returns floats
np.random.randn(5)

array([ 0.8943175 , -0.73121146, -1.25395584,  0.33535962, -0.42898748])

In [20]:
#can include negative numbers
#creates a 5x2 matrix with randomly generated numbers between 0(inclusive) and 1/-1(exclusive)
#returns floats
np.random.randn(5, 2)

array([[-0.67967512, -1.02815108],
       [-1.78499198,  1.75301359],
       [-1.971575  ,  0.81411842],
       [-0.24109239, -0.32545903],
       [-0.15842842, -0.4649102 ]])

In [21]:
#creates a one-dimensional array with randomly generated integers
#start(inclusive), stop(exclusive), shape
#returns floats
np.random.randint(0, 100, 5)

array([15, 96, 51, 64, 63])

In [22]:
#creates a 2d matrix array with randomly generated integers
#start(inclusive), stop(exclusive), shape
#returns floats
np.random.randint(0, 100, (4, 5))

array([[82, 73, 55, 24,  5],
       [17, 44, 82, 86, 51],
       [68, 97, 61, 73, 87],
       [86, 33, 11, 60, 91]])

In [23]:
#seed allows us to generate the same set of random numbers everytime we run the cell
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [24]:
temp_arr = np.arange(0, 25)

In [25]:
temp_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
#change shape of array from 1d to 5x5 matrix
#row x col must equal size of 1d array
temp_arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
rand_arr = np.random.randint(0, 101, 10)

In [28]:
rand_arr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [29]:
rand_arr.max()

99

In [30]:
rand_arr.min()

2

In [31]:
#index of max value in array
rand_arr.argmax()

5

In [32]:
#index of min value in array
rand_arr.argmin()

7

In [33]:
#data type of elements in array
rand_arr.dtype

dtype('int64')

In [34]:
#dimension of array
rand_arr.shape

(10,)

## NumPy Indexing and Selection

In [35]:
i_arr = np.arange(0, 10)

In [36]:
i_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
i_arr[5]

5

In [38]:
i_arr[1:5]

array([1, 2, 3, 4])

In [39]:
i_arr[:5]

array([0, 1, 2, 3, 4])

In [40]:
i_arr[5:]

array([5, 6, 7, 8, 9])

In [43]:
#broadcast a value accrcoss range range
#elements at position zero through 5 => 100
i_arr[0:5] = 100

In [44]:
i_arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [55]:
arr = np.arange(0, 11)

In [56]:
#still holds reference to original array
#so any changes in 'without' will affect 'arr'
without = arr[0:5]

In [59]:
without[:] = 99

In [60]:
without

array([99, 99, 99, 99, 99])

In [61]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [63]:
arr = np.arange(0, 11)

In [64]:
#does not hold reference to original array
#so any changes in 'without' will NOT affect 'arr'
copy_arr = arr.copy()

In [65]:
copy_arr[:] = 99

In [66]:
copy_arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [69]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [70]:
#give me element at row 1, column 2
arr_2d[1, 2]

30

In [72]:
#give me rows 0 - 2(exclusive), columns 1 - 2
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
arr = np.arange(0, 11)

In [73]:
#returns boolean array - true where condition is true and false otherwise
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [76]:
bool_arr = arr > 5

In [77]:
#returns all values in array that are true in boolean array
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [78]:
#same as above example
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

## NumPy Operations

**Remember you can't divide a number by zero**

In [85]:
arr = np.arange(1, 11)

In [86]:
#adds five to every element
arr + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [87]:
#subtracts five to every element
arr - 5

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [88]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [89]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [90]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [91]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [92]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [93]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [94]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [95]:
arr.sum()

55

In [96]:
arr.max()

10

In [98]:
arr.mean()

5.5

In [97]:
arr.mean()

5.5

In [99]:
arr.std()

2.8722813232690143

In [100]:
arr.var()

8.25

In [101]:
arr_2d = np.arange(0, 25).reshape(5, 5)

In [102]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [103]:
#sums all values in matrix
arr_2d.sum()

300

In [104]:
#sums each row
arr_2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [106]:
#sums each column
arr_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])